version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverdocker
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Nam@15112003
      - MSSQL_PID=Evaluation
    ports:
      - "1432:1433"
    networks:
      - mynetwork

  heartspace-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heartspace_api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
    ports:
      - "7000:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
